SOS/urls.py
from django.conf.urls import include,url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('buy_portal.urls')),

]

buy_portal/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='buy_portal'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login_user/$', views.login_user, name='login_user'),
     url(r'^logout_user/$', views.logout_user, name='logout_user'),
     url(r'^create_new_user/$', views.create_new_user, name='create_new_user'),
     url(r'^sell/$', views.sell, name='sell'),
     url(r'^advertise/$', views.advertise, name='advertise'),
     url(r'^requirement/$', views.requirement, name='requirement'),
     url(r'^item_detail/(?P<item_id>[0-9]+)$', views.item_detail, name='item_detail'),
    url(r'^adv_detail/(?P<adv_id>[0-9]+)$', views.adv_detail, name='adv_detail'),
    url(r'^my_activity/$', views.my_activity, name='my_activity'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

buy_portal/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from datetime import datetime
import os

CAT_CHOICES = (
    ('Other', 'Other'),
    ('Book', 'Book'),
    ('Instrument', 'Instrument'),
    ('Project', 'Project'),
)


def get_image_path(instance, filename):
    return os.path.join('photos', str(instance.id), filename)


class Item(models.Model):
    category = models.CharField(max_length=10, choices=CAT_CHOICES, default='Other')
    item_name=models.CharField(max_length=100)
    mrp_price=models.IntegerField()
    selling_price=models.IntegerField()
    image=models.FileField()
    description=models.CharField(max_length=100)
    datetime=models.DateTimeField(default=datetime.now, blank=True)
    user = models.ForeignKey(User, default=1,on_delete=models.CASCADE)

class Requirement(models.Model):
    user = models.ForeignKey(User, default=1,on_delete= models.CASCADE)
    title=models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    expected_price = models.IntegerField(default=0)
    datetime = models.DateTimeField(default=datetime.now, blank=True)

class Advertisement(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    image = models.FileField()
    datetime = models.DateTimeField(default=datetime.now, blank=True)

buy_portal/forms.py
from django import forms
from django.contrib.auth.models import User
from . models import Item,Advertisement,Requirement

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields=['category','item_name','mrp_price','selling_price','image','description']

class AdvertiseForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields=['title','image','description']

class RequirementForm(forms.ModelForm):
    class Meta:
        model = Requirement
        fields=['title','expected_price','description']

buy_portal/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from .forms import UserForm,ItemForm,AdvertiseForm,RequirementForm
from .models import Item,Advertisement

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'buy_portal/login.html')
    else:
        recent_objects = Item.objects.order_by('-datetime')[:6]
        book_objects = Item.objects.filter(category='Book')[:6]
        instruments_objects = Item.objects.filter(category='Instrument')[:6]
        projects_objects = Item.objects.filter(category='Project')[:6]
        other_objects = Item.objects.filter(category='Other')[:6]
        adv_objects=Advertisement.objects.order_by('-datetime')[:3]
        adv1=adv_objects[0]
        adv2 = adv_objects[1]
        adv3 = adv_objects[2]
        context = {
            'recent_objects': recent_objects,
            'book_objects':book_objects,
            'instruments_objects':instruments_objects,
            'projects_objects':projects_objects,
            'other_objects':other_objects,
            'adv1':adv1,
            'adv2': adv2,
            'adv3': adv3,
        }
        return render(request, 'buy_portal/Home.html',context)

def item_detail(request,item_id):
    if not request.user.is_authenticated():
        return render(request, 'buy_portal/login.html')
    else:
        item=Item.objects.get(pk=item_id)
        context={
            'item':item,
        }
        return render(request, 'buy_portal/item_detail.html', context)

def adv_detail(request,adv_id):
    if not request.user.is_authenticated():
        return render(request, 'buy_portal/login.html')
    else:
        adv=Advertisement.objects.get(pk=adv_id)
        context={
            'adv':adv,
        }
        return render(request, 'buy_portal/adv_detail.html', context)


def sell(request):
    if not request.user.is_authenticated():
        return render(request, 'buy_portal/login.html')
    else:
        form = ItemForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            item = form.save(commit=False)
            item.user=request.user
            item.image = request.FILES['image']
            file_type = item.image.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'buy_portal/sell.html', context)

            mrp_price = request.POST['mrp_price']
            selling_price = request.POST['selling_price']
            item_name = request.POST['item_name']
            char=str(item_name)[0]
            print type(char)
            if int(mrp_price)<int(selling_price) :
                if char<'A'or 'Z' < char < 'a' or char> 'z':
                    context = {
                        'form': form,
                        'error_message': 'Selling price should be less than MRP And  Item name should start with character!',
                    }
                    return render(request, 'buy_portal/sell.html', context)

                context = {
                    'form': form,
                    'error_message': 'Selling price should be less than MRP!',
                }
                return render(request, 'buy_portal/sell.html', context)
            elif char<'a'or char>'z' and char<'A'or char>'Z':
                    context = {
                        'form': form,
                        'error_message': 'Item name should start with character!',
                    }
                    return render(request, 'buy_portal/sell.html', context)


            item.save()
            return render(request, 'buy_portal/success.html')
        context={
            'form':form,
        }
        return render(request, 'buy_portal/sell.html',context)


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'buy_portal/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('buy_portal:index')  # redirect() accepts a view name as parameter
            else:
                return render(request, 'buy_portal/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'buy_portal/login.html', {'error_message': 'Invalid login'})
    return render(request, 'buy_portal/login.html')


def create_new_user(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        login(request, user)
        return redirect('buy_portal:index')
    context = {
             "form": form,
    }
    return render(request, 'buy_portal/create_new_user.html', context)

def advertise(request):
    if not request.user.is_authenticated():
        return render(request, 'buy_portal/login.html')
    else:
        form = AdvertiseForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            adv = form.save(commit=False)
            adv.user=request.user
            adv.image = request.FILES['image']
            file_type = adv.image.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'music/advertise.html', context)
            adv.save()
            return render(request, 'buy_portal/success.html')
        context={
            'form':form,
        }
        return render(request, 'buy_portal/advertise.html',context)

def requirement(request):
    if not request.user.is_authenticated():
        return render(request, 'buy_portal/login.html')
    else:
        form = RequirementForm(request.POST or None)
        if form.is_valid():
            req = form.save(commit=False)
            req.user=request.user
            req.save()
            return render(request, 'buy_portal/success.html')
        context={
            'form':form,
        }
        return render(request, 'buy_portal/requirement.html',context)

def my_activity(request):
    if not request.user.is_authenticated():
        return render(request, 'buy_portal/login.html')
    else:
        my_sells=Item.objects.filter(user=request.user)
        context = {
            'my_sells': my_sells,
        }
        return render(request, 'buy_portal/my_activity.html', context)

buy_portal/templates/buy_portal/Home.html
{% extends 'buy_portal/base.html' %}
{% block title %}Home{% endblock %}


{% block body %}
{% load staticfiles %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active ">
        <a href="{% url 'buy_portal:adv_detail' adv1.id %}">
      <img class="d-block img-fluid " src="{{adv1.image.url}}" alt="First slide">
        </a>
    </div>
    <div class="carousel-item">
        <a href="{% url 'buy_portal:adv_detail' adv2.id %}">
      <img class="d-block img-fluid" src="{{adv2.image.url}}" alt="Second slide">
        </a>
    </div>
    <div class="carousel-item">
        <a href="{% url 'buy_portal:adv_detail' adv3.id %}">
      <img class="d-block img-fluid" src="{{adv3.image.url}}" alt="Third slide">
        </a>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<nav class="navbar navbar-light" style="background-color: #424242">
  <!-- Navbar content -->
</nav>

<div class="container-fluid">
<p>
<h4>Recently Added!</h4>
</p>
<div class="row ">
{% for item in recent_objects %}
<div class="col-lg-2">
<div class="card" id="id_card" style="width: 10rem;">
      <div class="card-title">
        <h6>{{item.item_name}}</h6>
    </div>
  <div class="card-body text-center">
      <a href="#">
          {% if item.image %}
          <img class="card-img-bottom" src="{{ item.image.url }}" alt="Card image cap">
          {% else %}
            <h3>No image to display</h3>
          {% endif %}
      </a>
                <form>
                  <input type="button" value="Buy Now" class="btn btn-primary"
                         onclick="window.location.href='{% url 'buy_portal:item_detail' item.id %}'" />
                </form>
  </div>
</div>
</div>
{% endfor %}
</div>
<br>

<nav class="navbar navbar-light" style="background-color: #424242">
  <!-- Navbar content -->
</nav>


<p>
<h4>Books!</h4>
</p>

<br>
<div class="row">
{% for item in book_objects %}
<div class="col-lg-2">
<div class="card" style="width: 10rem;">
      <div class="card-title">
        <h6>{{item.item_name}}</h6>
    </div>
 <div class="card-body text-center">
      <a href="#">
          {% if item.image %}
          <img class="card-img-bottom" src="{{ item.image.url }}" alt="Card image cap">
          {% else %}
            <h3>No image to display</h3>
          {% endif %}
      </a>
                <form>
                  <input type="button" value="Buy Now" class="btn btn-primary"
                         onclick="window.location.href='{% url 'buy_portal:item_detail' item.id %}'" />
                </form>
  </div>
</div>
</div>
{% endfor %}
</div>
<br>

<nav class="navbar navbar-light" style="background-color: #424242">
  <!-- Navbar content -->
</nav>

<p>
<h4>Instruments!</h4>
</p>

<br>
<div class="row">
{% for item in instruments_objects %}
<div class="col-lg-2">
<div class="card" style="width: 10rem;">
      <div class="card-title">
        <h6>{{item.item_name}}</h6>
    </div>
  <div class="card-body text-center">
      <a href="#">
          {% if item.image %}
          <img class="card-img-bottom" src="{{ item.image.url }}" alt="Card image cap">
          {% else %}
            <h3>No image to display</h3>
          {% endif %}
      </a>
                <form>
                  <input type="button" value="Buy Now" class="btn btn-primary"
                         onclick="window.location.href='{% url 'buy_portal:item_detail' item.id %}'" />
                </form>
  </div>
</div>
</div>
{% endfor %}
</div>
<br>

<nav class="navbar navbar-light" style="background-color: #424242">
  <!-- Navbar content -->
</nav>

<p>
<h4>Projects!</h4>
</p>

<br>
<div class="row">
{% for item in projects_objects %}
<div class="col-lg-2">
<div class="card" style="width: 10rem;">
      <div class="card-title">
        <h6>{{item.item_name}}</h6>
    </div>
  <div class="card-body text-center">
      <a href="#">
          {% if item.image %}
          <img class="card-img-bottom" src="{{ item.image.url }}" alt="Card image cap">
          {% else %}
            <h3>No image to display</h3>
          {% endif %}
      </a>
                <form>
                  <input type="button" value="Buy Now" class="btn btn-primary"
                         onclick="window.location.href='{% url 'buy_portal:item_detail' item.id %}'" />
                </form>
  </div>
</div>
</div>
{% endfor %}
</div>
<br>

<nav class="navbar navbar-light" style="background-color: #424242">
  <!-- Navbar content -->
</nav>


<p>
<h4>Others!</h4>
</p>

<br>
<div class="row">
{% for item in other_objects %}
<div class="col-lg-2">
<div class="card" style="width: 10rem;">
      <div class="card-title">
        <h6>{{item.item_name}}</h6>
    </div>
  <div class="card-body text-center">
      <a href="#">
          {% if item.image %}
          <img class="card-img-bottom" src="{{ item.image.url }}" alt="Card image cap">
          {% else %}
            <h3>No image to display</h3>
          {% endif %}
      </a>
                <form>
                  <input type="button" value="Buy Now" class="btn btn-primary"
                         onclick="window.location.href='{% url 'buy_portal:item_detail' item.id %}'" />
                </form>
  </div>
</div>
</div>
{% endfor %}
</div>
<br>

</div>
<!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <!-- Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

{% endblock %}

buy_portal/templates/buy_portal/adv_detail.html
{% extends 'buy_portal/base.html' %}
{% block title %}Item Detail{% endblock %}


{% block body %}
<div class="container">
<div class="row">
<div class="col-lg-4">
<div class="card" style="width: 20rem;">
  <img class="card-img-top" src="{{ adv.image.url }}" alt="Card image cap">
  <div class="card-body">

  </div>
</div>
</div>
<div class="col-lg-6">
<p align="left">
<h3>{{adv.title}}</h3>
</p>

<br><br>

<p align="left">
<h4>Description:</h4>
{{adv.description}}
</p>
<br><br><br>



<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Interested
</button>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Cancel
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Message :</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
			we are configuring this module!
		</p>
      </div>
      <div class="modal-footer">
		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


</div>
</div>
</div>
<!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <!-- Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

{% endblock %}

buy_portal/templates/buy_portal/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Student's Online Store{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'buy_portal/style.css' %}"/>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

   <a class="navbar-brand" href="{% url 'buy_portal:index' %}">
    Home
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'buy_portal:sell' %}">Sell</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'buy_portal:advertise' %}">Post Advertise</a>
      </li>
        <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'buy_portal:requirement' %}">Requirements</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
     <ul class="navbar-nav mr-5">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"  id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{user.username}}
        </a>
        <div class="dropdown-menu animated flip mr-2" aria-labelledby="navbarDropdownMenuLink">
     <div class="dropdown-item mx-auto">
         <form>
             <input type="button" value="My Activity" class="btn btn-outline-secondary"
              onclick="window.location.href='{% url 'buy_portal:my_activity' %}'" />
         </form>

     </div>
            <div class="dropdown-item mx-auto">
         <form>
             <input type="button" value="Logout" class="btn btn-outline-secondary"
              onclick="window.location.href='{% url 'buy_portal:logout_user' %}'" />
         </form>

     </div>
 </div>
      </li>

    </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

buy_portal/templates/buy_portal/create_new_user.html
{% extends 'buy_portal/base_visitor.html' %}
{% block title %}Sign Up{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row mt-2">
<div class="col-sm-1">
	</div>
</div>

    <div class="row">
	<div class="col-sm-1">
	</div>
	<div class="col-sm-6">


          <div class="card">
				<div class="card-header p-b-0">
					<h5 class="card-title">
						Sign Up
					</h5>
				</div>
				<div class="card-block">
					<form class="form-group" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'buy_portal/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">SignUp</button>
                            </div>


                      </div>

                    </form>
                    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <!-- Navbar content -->
</nav>
                    <br>
      <div class="col-sm-offset-2 col-sm-10">
          <h6>Already have an account!</h6>
      </div>
      <br>
      <div class="col-sm-offset-2 col-sm-10">
      <form>
                  <input type="button" value="SignIn" class="btn btn-dark"
                         onclick="window.location.href='{% url 'buy_portal:login_user' %}'" />
              </form>
  </div>
                    <br>
				</div>
			</div>
        </div>
    </div>
</div>

<!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <!-- Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>


{% endblock %}

buy_portal/templates/buy_portal/login.html
{% extends 'buy_portal/base_visitor.html' %}
{% block title %}Sign In{% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row mt-2">
<div class="col-sm-1">
	</div>
</div>

    <div class="row">
	<div class="col-sm-1">
	</div>
	<div class="col-sm-6">
    <div class="card">
  <h4 class="card-header">Log In</h4>
  <div class="card-body">
    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'buy_portal:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-3" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-success">SignIn</button>
                            </div>
                        </div>
                    </form>
      <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <!-- Navbar content -->
</nav>
      <br>
      <div class="col-sm-offset-2 col-sm-10">
          <h6>Don't have account!</h6>
      </div>
      <br>
      <div class="col-sm-offset-2 col-sm-10">
      <form>
                  <input type="button" value="SignUp" class="btn btn-dark"
                         onclick="window.location.href='{% url 'buy_portal:create_new_user' %}'" />
              </form>
  </div>

                </div>
  </div>
</div>
    </div>
</div>

<!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <!-- Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

{% endblock %}